<div class='contenedor-artist-control'>

    <div style="padding-right: 100px;">
        <p style="font-size: 3em;">Control Panel</p>

    </div>
    <div style="padding-left: 100px;">
        <p style="font-size: 3em;">Agregar artista</p>

        <form id="" action='addArtista' method="post">

            <label for=''>Nombre artístico</label>
            <input type='text' name='artist-name'>

            <label for=''>Descripcion</label>
            <textarea name='artist-desc' id='' cols='30' rows='10'></textarea>

            <label for=''>Oferta</label>
            <select name="oferta" id="">
                <option value="">Si</option>
                <option value="">No</option>
            </select>

            <button type='submit'>Agregar</button>
        </form>
    </div>

</div>